# Generated by Django 5.2.7 on 2025-11-11 09:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.CharField(default='COD', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Tax rate as a whole percent (e.g., 12.00 for 12%)', max_digits=5),
        ),
    ]
