# Generated by Django 5.2.7 on 2025-11-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_purchaseorder_payment_terms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='tax_amount',
            new_name='tax_percent',
        ),
    ]
